title: Daniel Ng
description: Entrepreneur, Lawyer, and Roboticist building in AI.
url: "https://daniel.ventures"
baseurl: ""

permalink: /blog/:title/

exclude:
  - app-readyjetsetgo
  - node_modules
  - package.json
  - package-lock.json
  - .github